### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [kayru/Probulator#1]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/kayru/Probulator/blob/a54702a1905d8c5e124e3c2e6314b3a29f6f4a14/Source/ProbulatorCLI/Main.cpp#L260)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by kayru** [comment]
Hi,

Thanks for the links! Would you like to submit a patch that addresses your concerns? :)
While I don't see immediate need in top-level EH in this particular project, I also don't see any harm in adding it.

Yuriy

**Comment by elfring** [comment]
Would you like to [reconsider consequences from implementation-defined behaviour](http://stackoverflow.com/questions/5557555/raii-and-stack-unwinding)?
